export const gameConstants = {
    RATING_CREATE_REQUESTED: 'RATING_CREATE_REQUESTED',
    RATING_CREATED: 'RATING_CREATED',
    RATING_CREATE_FAIL: 'RATING_CREATE_FAIL',
    RATING_CREATE_FAIL_EXISTS: 'RATING_CREATE_FAIL_EXISTS',

    RATING_UPDATED: 'RATING_UPDATED',
    RATING_UPDATE_FAIL: 'RATING_UPDATE_FAIL',

    RATINGS_FETCHED: 'RATINGS_FETCHED',
    RATING_FETCH_FAIL: 'RATING_FETCH_FAIL',

    GAMES_FETCHED: 'GAMES_FETCHED',
    GAME_FETCH_FAIL: 'GAME_FETCH_FAIL'
}