export const userConstants = {
    LOGIN_REQUESTED: 'LOGIN_REQUESTED',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    REGISTER_LOADING: 'REGISTER_LOADING',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    LOGOUT: 'LOGOUT'
}